*.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
*.sink.prometheusServlet.path=/metrics/prometheus
master.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
master.sink.prometheusServlet.path=/metrics/prometheus
worker.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
worker.sink.prometheusServlet.path=/metrics/prometheus
